#HAL - Happy App Land
#First simple deploy, some post config required(portainer, nexcloud, cortex)
#Homer files not yet updated 
#still need to add in ticket system 

version: "3.8"

services:
  homer:
    image: b4bz/homer:latest
    container_name: homer
    ports:
      - "8080:8080"
    volumes:
      - ./homer/assets:/www/assets
    networks:
      - custom_network
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    command: >-
      -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - custom_network
    restart: unless-stopped

  cyberchef:
    image: mpepping/cyberchef:latest
    container_name: cyberchef
    ports:
      - "8000:8000"
    networks:
      - custom_network
    restart: unless-stopped

  etherpad:
    image: etherpad/etherpad:latest
    container_name: etherpad
    ports:
      - "9001:9001"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=etherpad_db
      - DB_PORT=3306
      - DB_USER=etherpad
      - DB_PASSWORD=padpass
      - DB_NAME=etherpad
    depends_on:
      - etherpad_db
    networks:
      - custom_network
    restart: unless-stopped

  etherpad_db:
    image: mariadb:10.5
    container_name: etherpad_db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=etherpad
      - MYSQL_USER=etherpad
      - MYSQL_PASSWORD=padpass
    volumes:
      - etherpad_db_data:/var/lib/mysql
    networks:
      - custom_network
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=superstrongpass!23
      - N8N_SECURE_COOKIE=false
      - TZ=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - custom_network
    restart: unless-stopped

  ittools:
    image: corentinth/it-tools:latest
    container_name: ittools
    ports:
      - "8081:80"
    networks:
      - custom_network
    restart: unless-stopped

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8082:80"
    environment:
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=Superstrongpass!23
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - custom_network
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - custom_network
    restart: unless-stopped

  cortex:
    image: thehiveproject/cortex:latest
    container_name: cortex
    ports:
      - "9003:9001"
    environment:
      - JOB_DIRECTORY=/opt/cortex/jobs
      - CORTEX_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - custom_network
    restart: unless-stopped

networks:
  custom_network:
    driver: bridge


volumes:
  portainer_data:
  n8n_data:
  nextcloud_data:
  elastic_data:
  etherpad_db_data:
