                                                                                                                                       
services:
  zeek:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeek_container
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/logs
    ports:
      - "47760:47760"
    command: ["zeek", "-i", "eth0"]
