                                                                                                                                       
services:
  zeek:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zeek_container
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/logs
    command: ["zeek", "-i", "ens33"]


  suricata:
    image: jasonish/suricata:latest   # Suricata IDS image
    container_name: suricata-container
    network_mode: host                # Use the host's network stack (including ens33)
    restart: always
    cap_add:
      - NET_ADMIN                    # Necessary for Suricata to capture network traffic
    environment:
      - SURICATA_HOME=/etc/suricata   # Path to Suricata config directory
    volumes:
      - ./suricata/config:/etc/suricata   # Mount your custom Suricata config
      - ./suricata/logs:/var/log/suricata # Mount log directory for Suricata
      - /etc/suricata/rules:/etc/suricata/rules  # Mount rules directory
    command: ["suricata", "-c", "/etc/suricata/suricata.yaml", "-i", "ens33"]  # Use ens33 interface


  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.7.0  # Elastic Agent image
    container_name: elastic-agent
    restart: always
    environment:
      - ELASTICSEARCH_HOST=http://elasticsearch:9200  # Replace with actual Elasticsearch URL
      - KIBANA_HOST=http://kibana:5601                # Replace with actual Kibana URL
      - ELASTICSEARCH_USERNAME=elastic                # Set your Elasticsearch username
      - ELASTICSEARCH_PASSWORD=your-password-here     # Set your Elasticsearch password
    networks:
      - HIL
    volumes:
      - ./elastic-agent/config:/usr/share/elastic-agent/config  # Mount your config folder (optional)
    command: >
      /usr/share/elastic-agent/elastic-agent enroll
      --url=http://fleet-server:8220                      # URL to Fleet Server (if you have one)
      --enrollment-token=your-enrollment-token-here        # Replace with your enrollment token
      --insecure                                          # Optional: Skip TLS validation (useful for testing)
    depends_on:
      - elasticsearch
      - kibana

networks:
  HIL:
    driver: bridge


  portainer-agent:
    image: portainer/agent:2.21.4
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"  # Expose the agent API on port 9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock       # Allow Docker socket access
      - /var/lib/docker/volumes:/var/lib/docker/volumes # Mount Docker volumes directory
      - /:/host                                          # Mount the root filesystem to /host
    networks:
      - HIL

networks:
  HIL:
    driver: bridge
